# Generated by Django 6.0.6 on 2026-07-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, чтобы опубликовать продукт",
                verbose_name="Опубликовано",
            ),
        ),
    ]
